/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as ProfileIndexImport } from './routes/profile/index';
import { Route as FillingQuestionnaireIndexImport } from './routes/filling-questionnaire/index';
import { Route as ClientRecommendationsIndexImport } from './routes/client-recommendations/index';
import { Route as ChatWithCuratorIndexImport } from './routes/chat-with-curator/index';
import { Route as SpecialistsConsultationSelectImport } from './routes/specialists/consultation-select';
import { Route as SpecialistsConsultationTypeIdConsultationAppointmentImport } from './routes/specialists/$consultationTypeId.consultation-appointment';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any);

const FillingQuestionnaireIndexRoute = FillingQuestionnaireIndexImport.update({
  id: '/filling-questionnaire/',
  path: '/filling-questionnaire/',
  getParentRoute: () => rootRoute,
} as any);

const ClientRecommendationsIndexRoute = ClientRecommendationsIndexImport.update({
  id: '/client-recommendations/',
  path: '/client-recommendations/',
  getParentRoute: () => rootRoute,
} as any);

const ChatWithCuratorIndexRoute = ChatWithCuratorIndexImport.update({
  id: '/chat-with-curator/',
  path: '/chat-with-curator/',
  getParentRoute: () => rootRoute,
} as any);

const SpecialistsConsultationSelectRoute = SpecialistsConsultationSelectImport.update({
  id: '/specialists/consultation-select',
  path: '/specialists/consultation-select',
  getParentRoute: () => rootRoute,
} as any);

const SpecialistsConsultationTypeIdConsultationAppointmentRoute =
  SpecialistsConsultationTypeIdConsultationAppointmentImport.update({
    id: '/specialists/$consultationTypeId/consultation-appointment',
    path: '/specialists/$consultationTypeId/consultation-appointment',
    getParentRoute: () => rootRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/specialists/consultation-select': {
      id: '/specialists/consultation-select';
      path: '/specialists/consultation-select';
      fullPath: '/specialists/consultation-select';
      preLoaderRoute: typeof SpecialistsConsultationSelectImport;
      parentRoute: typeof rootRoute;
    };
    '/chat-with-curator/': {
      id: '/chat-with-curator/';
      path: '/chat-with-curator';
      fullPath: '/chat-with-curator';
      preLoaderRoute: typeof ChatWithCuratorIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/client-recommendations/': {
      id: '/client-recommendations/';
      path: '/client-recommendations';
      fullPath: '/client-recommendations';
      preLoaderRoute: typeof ClientRecommendationsIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/filling-questionnaire/': {
      id: '/filling-questionnaire/';
      path: '/filling-questionnaire';
      fullPath: '/filling-questionnaire';
      preLoaderRoute: typeof FillingQuestionnaireIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/profile/': {
      id: '/profile/';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof ProfileIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/specialists/$consultationTypeId/consultation-appointment': {
      id: '/specialists/$consultationTypeId/consultation-appointment';
      path: '/specialists/$consultationTypeId/consultation-appointment';
      fullPath: '/specialists/$consultationTypeId/consultation-appointment';
      preLoaderRoute: typeof SpecialistsConsultationTypeIdConsultationAppointmentImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/specialists/consultation-select': typeof SpecialistsConsultationSelectRoute;
  '/chat-with-curator': typeof ChatWithCuratorIndexRoute;
  '/client-recommendations': typeof ClientRecommendationsIndexRoute;
  '/filling-questionnaire': typeof FillingQuestionnaireIndexRoute;
  '/profile': typeof ProfileIndexRoute;
  '/specialists/$consultationTypeId/consultation-appointment': typeof SpecialistsConsultationTypeIdConsultationAppointmentRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/specialists/consultation-select': typeof SpecialistsConsultationSelectRoute;
  '/chat-with-curator': typeof ChatWithCuratorIndexRoute;
  '/client-recommendations': typeof ClientRecommendationsIndexRoute;
  '/filling-questionnaire': typeof FillingQuestionnaireIndexRoute;
  '/profile': typeof ProfileIndexRoute;
  '/specialists/$consultationTypeId/consultation-appointment': typeof SpecialistsConsultationTypeIdConsultationAppointmentRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/specialists/consultation-select': typeof SpecialistsConsultationSelectRoute;
  '/chat-with-curator/': typeof ChatWithCuratorIndexRoute;
  '/client-recommendations/': typeof ClientRecommendationsIndexRoute;
  '/filling-questionnaire/': typeof FillingQuestionnaireIndexRoute;
  '/profile/': typeof ProfileIndexRoute;
  '/specialists/$consultationTypeId/consultation-appointment': typeof SpecialistsConsultationTypeIdConsultationAppointmentRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/specialists/consultation-select'
    | '/chat-with-curator'
    | '/client-recommendations'
    | '/filling-questionnaire'
    | '/profile'
    | '/specialists/$consultationTypeId/consultation-appointment';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/specialists/consultation-select'
    | '/chat-with-curator'
    | '/client-recommendations'
    | '/filling-questionnaire'
    | '/profile'
    | '/specialists/$consultationTypeId/consultation-appointment';
  id:
    | '__root__'
    | '/'
    | '/specialists/consultation-select'
    | '/chat-with-curator/'
    | '/client-recommendations/'
    | '/filling-questionnaire/'
    | '/profile/'
    | '/specialists/$consultationTypeId/consultation-appointment';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SpecialistsConsultationSelectRoute: typeof SpecialistsConsultationSelectRoute;
  ChatWithCuratorIndexRoute: typeof ChatWithCuratorIndexRoute;
  ClientRecommendationsIndexRoute: typeof ClientRecommendationsIndexRoute;
  FillingQuestionnaireIndexRoute: typeof FillingQuestionnaireIndexRoute;
  ProfileIndexRoute: typeof ProfileIndexRoute;
  SpecialistsConsultationTypeIdConsultationAppointmentRoute: typeof SpecialistsConsultationTypeIdConsultationAppointmentRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpecialistsConsultationSelectRoute: SpecialistsConsultationSelectRoute,
  ChatWithCuratorIndexRoute: ChatWithCuratorIndexRoute,
  ClientRecommendationsIndexRoute: ClientRecommendationsIndexRoute,
  FillingQuestionnaireIndexRoute: FillingQuestionnaireIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SpecialistsConsultationTypeIdConsultationAppointmentRoute:
    SpecialistsConsultationTypeIdConsultationAppointmentRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/specialists/consultation-select",
        "/chat-with-curator/",
        "/client-recommendations/",
        "/filling-questionnaire/",
        "/profile/",
        "/specialists/$consultationTypeId/consultation-appointment"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/specialists/consultation-select": {
      "filePath": "specialists/consultation-select.tsx"
    },
    "/chat-with-curator/": {
      "filePath": "chat-with-curator/index.ts"
    },
    "/client-recommendations/": {
      "filePath": "client-recommendations/index.tsx"
    },
    "/filling-questionnaire/": {
      "filePath": "filling-questionnaire/index.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/specialists/$consultationTypeId/consultation-appointment": {
      "filePath": "specialists/$consultationTypeId.consultation-appointment.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
